apiVersion: v1
name: outline
description: The outline helm chart to deploy outline in kubernetes clusters.
version: 0.0.8
appVersion: 0.69.1
home: https://encircle360.com
sources:
  - https://gitlab.com/encircle360-oss/helm-charts/outline
  - https://github.com/encircle360-oss/outline-helm-chart
keywords:
  - outline
  - wiki
  - helm
  - chart
  - kubernetes
  - s3
  - minio
  - postgresql
  - mongodb
  - knowledge
maintainers:
  - name: encircle360 GmbH
    email: hello@encircle360.com
    url: https://encircle360.com

dependencies:
  - name: postgresql
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 10.12.2
    alias: postgresql
    condition: postgresql.enabled
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 15.4.1
    alias: redis
    condition: redis.enabled
  - name: minio
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 7.2.0
    alias: minio
    condition: minio.enabled
