name: outline
image:
  repository: outlinewiki/outline
  tag: 0.79.1
  pullPolicy: IfNotPresent
replicas: 1
resources: {}
env:
  # SLACK_KEY: "slack key in slack oidc context"
  # SLACK_SECRET: "slack secret in slack oidc context"
envSecrets:

ingress:
  host: outline.yourdomain.tld
  annotations: # set your custom ingress annotations here
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    enabled: false
podLabels: {}

redis:
  enabled: true
  architecture: "standalone"
  persistence:
    size: 2Gi
    storageClass: ""
  auth:
    enabled: false

postgresql:
  enabled: true
  architecture: "standalone"
  postgresqlDatabase: "outline"
  postgresqlUsername: "outline"
  postgresqlPassword: "vh4rf^q32BcvtFqFVjny4pnM" # MUST be replaced with some secret password! Don't use this in production
  postgresqlPostgresPassword: "Ma#wXFMz6jFqXUr^qP&K66XQbd" # MUST be replaced with some secret password! Don't use this in production
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi

minio:
  enabled: true
  disableWebUI: false
  ingress:
    enabled: true
    hostname: data.outline.yourdomain.tld
    certManager: false
    tls: false
    annotations:
      # cert-manager.io/cluster-issuer: "letsencrypt-staging"
  mode: "standalone"
  defaultBuckets: "ol-data" # should not be "outline" because of https://github.com/outline/outline/issues/2068
  secretKey:
    password: "Uk4LuwVFvRDiG6k4nYA5C^835V" # MUST be replaced with some custom generated secret! Don't use this in production
  accessKey:
    password: "zFPVNNK*QNp3^V4J38Gy76SehG" # MUST be replaced with some custom generated access_key! Don't use this in production
  persistence:
    enabled: true
    storageClass: ""
    size: 2Gi
