apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  secretKey: |
    {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.name -}}
    {{- if and $secret $secret.data.secretKey }}
      {{ $secret.data.secretKey }}
    {{- else }}
      {{ include "jupyterhub.randHex" 64 | b64enc }}
    {{- end }}
  utilsSecret: |
    {{- if and $secret $secret.data.utilsSecret }}
      {{ $secret.data.utilsSecret }}
    {{- else }}
      {{ include "jupyterhub.randHex" 64 | b64enc }}
    {{- end }}
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
