apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: web
  selector:
    app: {{ .Values.name }}